// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhsVluo06VJjT5Zx1N9_dOfyxyu7CTUGM',
    appId: '1:154405777224:web:59d55823b87d18dd7f4d7d',
    messagingSenderId: '154405777224',
    projectId: 'gasapp-3ed4f',
    authDomain: 'gasapp-3ed4f.firebaseapp.com',
    storageBucket: 'gasapp-3ed4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQbBVNU0tsqAxBbAfRoISB8cJvncv5XTQ',
    appId: '1:154405777224:android:4b43be4763f05fa67f4d7d',
    messagingSenderId: '154405777224',
    projectId: 'gasapp-3ed4f',
    storageBucket: 'gasapp-3ed4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBst-FyKs7qt2icE61teL9gs-VE4NHbxEs',
    appId: '1:154405777224:ios:9ce4b3ce49f491847f4d7d',
    messagingSenderId: '154405777224',
    projectId: 'gasapp-3ed4f',
    storageBucket: 'gasapp-3ed4f.firebasestorage.app',
    iosBundleId: 'com.example.gas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBst-FyKs7qt2icE61teL9gs-VE4NHbxEs',
    appId: '1:154405777224:ios:9ce4b3ce49f491847f4d7d',
    messagingSenderId: '154405777224',
    projectId: 'gasapp-3ed4f',
    storageBucket: 'gasapp-3ed4f.firebasestorage.app',
    iosBundleId: 'com.example.gas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhsVluo06VJjT5Zx1N9_dOfyxyu7CTUGM',
    appId: '1:154405777224:web:d2e1502868fac07f7f4d7d',
    messagingSenderId: '154405777224',
    projectId: 'gasapp-3ed4f',
    authDomain: 'gasapp-3ed4f.firebaseapp.com',
    storageBucket: 'gasapp-3ed4f.firebasestorage.app',
  );

}